### ISSUE TITLE
Line?

### ISSUE THREAD

**Issue by ricleal** [hville/node-scatterplot#1]
Hi!
Nice job!
In the `gif` you have a line plot?
How do you get that?
Looking forward to your reply.
Thanks

**Comment by hville** [comment]
Hi. Only scatterplots are supported and the line shown is really just a lot of really close points ;)

The [dygraph library](http://dygraphs.com/) supports lots more but I only needed scatterplots while developing [walk-z](https://github.com/hville/walk-z)

**Comment by ricleal** [comment]
Thanks for the reply. I appreciate it!
